const def_poster = 'https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1565865793087&di=94fbe3bc7b713c40288c12a6c44b3904&imgtype=0&src=http%3A%2F%2F5b0988e595225.cdn.sohucs.com%2Fimages%2F20171001%2Fe3a0f4f4c49649718e8773467cc2cb37.jpeg';

const def_videoUrl1 = 'https://gslb.miaopai.com/stream/HNkFfNMuhjRzDd-q6j9qycf54OaKqInVMu0YhQ__.mp4?ssig=bbabfd7684cae53660dc2d4c2103984e&time_stamp=1533631567740&cookie_id=&vend=1&os=3&partner=1&platform=2&cookie_id=&refer=miaopai&scid=HNkFfNMuhjRzDd-q6j9qycf54OaKqInVMu0YhQ__';

const def_videoUrl2 = 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';

const defSongList = {
  title: "我创建的歌单",
  list: [
    {
      id: 1,
      title: "我喜欢的音乐",
      isLove: true,
      love: "心动模式",
      all: 434,
      download: 218,
      isSing: false,
    },
    {
      id: 1565740902007,
      title: "最近听的",
      isLove: false,
      love: "非心动模式",
      all: 100,
      download: 30,
      isSing: true,
    },
    {
      id: 1565750902007,
      title: "周杰伦",
      isLove: false,
      love: "非心动模式",
      all: 200,
      download: 0,
      isSing: false,
    },
    {
      id: 1565760902007,
      title: "林俊杰",
      isLove: false,
      love: "非心动模式",
      all: 227,
      download: 0,
      isSing: false,
    }
  ]
};

const defFireScroll = [
  {
    id: 1,
    title: "因乐交友"
  },
  {
    id: 2,
    title: "私人FM"
  },
  {
    id: 3,
    title: "最新电音"
  },
  {
    id: 4,
    title: "Sati空间"
  },
  {
    id: 5,
    title: "私藏推荐"
  },
  {
    id: 6,
    title: "亲子频道"
  },
  {
    id: 7,
    title: "古典专区"
  }
];

const defFireNav = [
  {
    id: 1,
    title: '本地音乐',
    number: 220,
    icon: null,
  },{
    id: 2,
    title: '最近播放',
    number: 102,
    icon: null,
  },{
    id: 3,
    title: '我的电台',
    number: 0,
    icon: null,
  },{
    id: 4,
    title: '我的收藏',
    number: 6,
    icon: null,
  },
]

const defVideoList = [
  {
    id: 1565740102107,
    type: 0,
    number: 53151,
    time: 97000,
    title: '大师傅务器而发生的选择不持续成长',
    author: 'gdj',
    like: 481,
    messageNumber: 59,
    au_Img: null,
    title_img: null,
    video: def_videoUrl1,
    poster: def_poster,
  },
  {
    id: 1565740002107,
    type: 2,
    number: 2105,
    time: 60000,
    title: '啊的说法是的发生发的发的发的顺丰萨芬',
    author: '音乐秀',
    like: 211,
    messageNumber: 22,
    au_Img: null,
    title_img: null,
    video: def_videoUrl2,
    poster: def_poster,
  },
  {
    id: 1565730002107,
    type: 1,
    number: 105,
    time: 97000,
    title: '对方是否合适的非官方的身高多少',
    author: '流行音乐',
    like: 33,
    messageNumber: 12,
    au_Img: null,
    title_img: null,
    video: def_videoUrl1,
    poster: def_poster,
  },
]

const defSongListData = [
  {
    id: 1,
    name: '不朽之罪',
    editor: '双笙/玄觞',
    details: '【双笙/玄觞】 不朽之罪',
    url: 'http://music.163.com/song/media/outer/url?id=461687747.mp3',
    isSQ: false,
    isMV: false,
    isCloud: true,
    isDownload: true,
    isExclusive: false,
    isSelect: false,
  },
  {
    id: 2,
    name: '红昭愿',
    editor: '音阙诗听',
    details: '【音阙诗听】 红昭愿',
    url: 'http://music.163.com/song/media/outer/url?id=452986458.mp3',
    isSQ: true,
    isMV: true,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },
  {
    id: 3,
    name: '一眼万年',
    editor: '林俊杰',
    details: '林俊杰 - 她说 概念自选集',
    url: 'http://music.163.com/song/media/outer/url?id=108254.mp3',
    isSQ: true,
    isMV: false,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },
  {
    id: 4,
    name: '我曾 (女生版）',
    editor: '灿烂C.L',
    details: '灿烂C.L 我曾 (女生版）',
    url: 'http://music.163.com/song/media/outer/url?id=1357477356.mp3',
    isSQ: false,
    isMV: true,
    isCloud: true,
    isDownload: true,
    isExclusive: true,
    isSelect: false,
  },
  {
    id: 5,
    name: '背对背的拥抱',
    editor: '林俊杰',
    details: '林俊杰 - 100天',
    url: 'http://music.163.com/song/media/outer/url?id=108418.mp3',
    isSQ: true,
    isMV: false,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },
  {
    id: 6,
    name: '原来',
    editor: '林俊杰',
    details: '林俊杰 - 曹操',
    url: 'http://music.163.com/song/media/outer/url?id=108806.mp3',
    isSQ: true,
    isMV: true,
    isCloud: false,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },
  {
    id: 7,
    name: '绿色',
    editor: '陈雪凝',
    details: '陈雪凝 - 绿色',
    url: 'http://music.163.com/song/media/outer/url?id=1345848098.mp3',
    isSQ: true,
    isMV: false,
    isCloud: false,
    isDownload: true,
    isExclusive: true,
    isSelect: false,
  },
  {
    id: 8,
    name: '出山',
    editor: '花粥/王胜男',
    details: '花粥/王胜男 - 粥请客（四）',
    url: 'http://music.163.com/song/media/outer/url?id=1313354324.mp3',
    isSQ: true,
    isMV: true,
    isCloud: false,
    isDownload: true,
    isExclusive: true,
    isSelect: false,
  },{
    id: 9,
    name: '盗将行',
    editor: '花粥/马雨阳',
    details: '花粥/马雨阳 - 粥请客（二）',
    url: 'http://music.163.com/song/media/outer/url?id=574566207.mp3',
    isSQ: true,
    isMV: true,
    isCloud: false,
    isDownload: false,
    isExclusive: true,
    isSelect: false,
  },{
    id: 10,
    name: '追光者（电视剧《夏至未至》插曲）',
    editor: '岑宁儿',
    details: '岑宁儿 - 夏至未至 影视原声带',
    url: 'http://music.163.com/song/media/outer/url?id=483671599.mp3',
    isSQ: true,
    isMV: true,
    isCloud: false,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },{
    id: 11,
    name: '光年之外（电影《太空旅客》中文主题曲）',
    editor: 'G.E.M.邓紫棋',
    details: 'G.E.M.邓紫棋 - 光年之外',
    url: 'http://music.163.com/song/media/outer/url?id=449818741.mp3',
    isSQ: true,
    isMV: true,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },{
    id: 12,
    name: '修炼爱情',
    editor: '林俊杰',
    details: '林俊杰 - 因你而在',
    url: 'http://music.163.com/song/media/outer/url?id=25727803.mp3',
    isSQ: true,
    isMV: true,
    isCloud: false,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },{
    id: 13,
    name: '彩虹',
    editor: '周杰伦',
    details: '周杰伦 - 我很忙',
    url: 'http://dl.stream.qqmusic.qq.com/C100004bRWFg3fej9y.m4a?fromtag=38',
    isSQ: true,
    isMV: true,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },{
    id: 14,
    name: '星晴',
    editor: '周杰伦',
    details: '周杰伦 - Jay同名专辑',
    url: 'http://dl.stream.qqmusic.qq.com/C100001Zi7Ly4ZtVQk.m4a?fromtag=38',
    isSQ: true,
    isMV: true,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },{
    id: 15,
    name: '青花瓷',
    editor: '周杰伦',
    details: '周杰伦 - 我很忙',
    url: 'http://dl.stream.qqmusic.qq.com/C100002qU5aY3Qu24y.m4a?fromtag=38',
    isSQ: true,
    isMV: false,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },{
    id: 16,
    name: '发如雪',
    editor: '周杰伦',
    details: '周杰伦 - 十一月的肖邦',
    url: 'http://dl.stream.qqmusic.qq.com/C1000027oMO61wWi55.m4a?fromtag=38',
    isSQ: true,
    isMV: true,
    isCloud: true,
    isDownload: false,
    isExclusive: false,
    isSelect: false,
  },
]

export {
  defSongList,
  defFireScroll,
  defFireNav,
  defVideoList,
  def_poster,
  def_videoUrl1,
  def_videoUrl2,
  defSongListData,
};
